### ISSUE TITLE
Markbot error

### ISSUE THREAD

**Issue by emahadzimustafic** [emahadzimustafic/animated-clock#1]
Hello, here I am again with my weekly markbot errors.

It says I have a spacing error on line 16 but I don't? Can you confirm this @thatkidmadrid?

![line 16](https://user-images.githubusercontent.com/77508090/142741860-5ead573b-b2ff-4a09-a81f-a990347136a3.JPG)
![markbox error](https://user-images.githubusercontent.com/77508090/142741861-38ed9a1c-3395-4821-b483-6cca2092e5d8.JPG)

**Comment by thatkidmadrid** [comment]
it's referring to your `index.html` not your `main.css`!

**Comment by emahadzimustafic** [comment]
Ah, I should've looked closer. Thank you.
